baseURL = "https://choubsi.roudy.xyz"
title   = "Choubsi"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[pagination]
  disableAliases = false
  pagerSize = 20
  path = 'page'

[services]
  [services.rss]
      # Maximum number of items in the RSS feed.
      limit = 42

[permalinks]
  posts = "/posts/:year/:month/:title/"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params]
  dateform        = "May 4th, 2025"
  dateformShort   = "May 4"
  dateformNum     = "2025-05-04"
  dateformNumTime = "2025-05-04 20:08"

  # Metadata mostly used in document's head
  # 
  description = "Nice theme for homepages and blogs"
  keywords = ""
  images = [""]
  
  homeSubtitle = "Karlus"
  disableReadOtherPosts = false
  enableThemeToggle = false
  enableSharingButtons = true
  enableGlobalLanguageMenu = false

  customCSS = []
  customJS  = []

  justifyContent = false

    [params.author]
    name = "Jane Doe"

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  [params.footer]
    trademark = 2023
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"
    ]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ cd /home/"
    logoHomeLink = "/"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/choubsi"

  [[params.social]]
    name = "TikTok"
    url  = "https://tiktok.com/@kiidskit"

  [[params.social]]
    name = "YouTube"
    url  = "https://youtube.com/@choubsi"

  [languages]
  [languages.en]
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  [languages.en.params]
    subtitle  = "Hello Friend NG Theme"

  [languages.fr]
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  [languages.fr.params]
    subtitle  = "Hello Friend NG Theme"
